### ISSUE TITLE
[solved] manually creating a shortname

### ISSUE THREAD

**Issue by spiralofhope** [tylerhall/simple-url-shortener#4]
I would like to create a custom shortlink, and not use a randomly-generated one.

I am trying to create `http://example.com/youtube`.  I see no feature built-in, which is fine, so I thought I could do it manually.  Steps I took:

- Used phpMyAdmin
- On the left, clicked `links` to view that table.
- clicked `copy` on the bottom entry
- incremented `id`
- set `slug` to "youtube"
- set `url` to the URL I want
- clicked `go` to save my chages
- visited `http://example.com/youtube`

I get a blank page (no content)

---

My shortlink is randomly generated into 5-characters, where "youtube" is 7.  I don't know if that causes a problem.

---

I'm not sure how to investigate this from here.

**Comment by MasterOfTheTiger** [comment]
I was going to implement this as well, but the actual code of the program should be easily changed to support this. Is that correct, maintainer?

**Comment by tylerhall** [comment]
@spiralofhope Did you literally choose "youtube" as your slug? Or was that just an example? I ask because the default 'config.php' file has a setting for the allowed characters that can be in the short link. The default choice avoids ambiguous characters like 0, o, 1, l, etc. And "youtube" contains "o", which is not allowed. That's probably the reason it didn't work.

@masterofthetiger I'd happily accept a pull request if you'd like to implement custom slugs 😀

**Comment by spiralofhope** [comment]
yes, I literally used the slug `youtube`.

I'll examine the allowed characters, I think that's probably the solution.

**Comment by spiralofhope** [comment]
I confirmed that my problem was within `config.php`.  I added `o` to the end.

```
$valid_chars = 'abcdefghjkmnpqrstuvwxyz23456789';
=>
$valid_chars = 'abcdefghjkmnpqrstuvwxyz23456789o';
```

Now technically I don't want to have `o` in the list of randomly-generated links, but I know how to edit them manually if I cared enough.  :)

**Comment by tylerhall** [comment]
👍

**Comment by MasterOfTheTiger** [comment]
@tylerhall Before I add full support for custom urls, I think we can avoid this by making two variables, $valid_chars and $random_chars. The $random_chars will be the same, but $valid_chars will be wider, and will include all accepted input for custom characters. 

Does that sound good? If so, I am making a pull request to implement this now.

**Comment by tylerhall** [comment]
@MasterOfTheTiger 👍

**Comment by spiralofhope** [comment]
So this would allow me to manually create "invalid for randomly-generated" and "valid for manually-generated" links?

Sounds good, as long as it doesn't bloat the code too much.  :)

**Comment by tylerhall** [comment]
@spiralofhope Yeah, the script would generate a random slug from one specific set of characters, but accept slugs from a different set. That would make sure the random ones are still readable (which was the original intent - to skip confusing characters like i, l, 1, o, 0), but still allow you to pick any manual slug you want.
